-- CreateEnum
CREATE TYPE "NotificationModule" AS ENUM ('INVENTORY', 'PROCUREMENT', 'WAREHOUSE', 'DISTRIBUTION', 'FINANCE', 'SUPPLIER_PAYMENT', 'BRANCH_ORDERS', 'SYSTEM');

-- AlterEnum
ALTER TYPE "AlertType" ADD VALUE 'INVENTORY_SUBMITTED';
ALTER TYPE "AlertType" ADD VALUE 'INVENTORY_APPROVED';
ALTER TYPE "AlertType" ADD VALUE 'INVENTORY_REJECTED';
ALTER TYPE "AlertType" ADD VALUE 'PROCUREMENT_CREATED';
ALTER TYPE "AlertType" ADD VALUE 'PROCUREMENT_WAITING_APPROVAL';
ALTER TYPE "AlertType" ADD VALUE 'PROCUREMENT_STATUS_CHANGED';
ALTER TYPE "AlertType" ADD VALUE 'GOODS_ARRIVED_FROM_CHINA';
ALTER TYPE "AlertType" ADD VALUE 'GOODS_RECEIVED_HQ';
ALTER TYPE "AlertType" ADD VALUE 'SUPPLIER_PAYMENT_DUE';
ALTER TYPE "AlertType" ADD VALUE 'SUPPLIER_PAYMENT_COMPLETED';

-- AlterEnum
ALTER TYPE "AlertStatus" ADD VALUE 'ARCHIVED';

-- AlterTable
ALTER TABLE "Alert" ADD COLUMN "module" "NotificationModule",
ADD COLUMN "recipientRole" "Role",
ADD COLUMN "referenceNumber" TEXT,
ADD COLUMN "archivedAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "Alert_module_idx" ON "Alert"("module");
CREATE INDEX "Alert_recipientRole_idx" ON "Alert"("recipientRole");
CREATE INDEX "Alert_referenceNumber_idx" ON "Alert"("referenceNumber");
