import type { DeleteStep } from './operational-cleanup.util';

export const TEST_DATA_CLEANUP_CATEGORIES = [
  'employees',
  'customers',
  'products',
  'purchases',
  'warehouse',
  'branchOrders',
  'sales',
  'finance',
  'all',
] as const;

export type TestDataCleanupCategory = (typeof TEST_DATA_CLEANUP_CATEGORIES)[number];

export const ALL_TEST_DATA_CONFIRMATION = 'DELETE ALL TEST DATA';

/** Prisma delete steps per cleanup category (children before parents). */
export const CLEANUP_CATEGORY_STEPS: Record<
  Exclude<TestDataCleanupCategory, 'all'>,
  DeleteStep[]
> = {
  sales: [
    'saleFifoAllocation',
    'saleInstallmentPayment',
    'saleInstallmentApproval',
    'salesCommission',
    'receipt',
    'payment',
    'installmentSchedule',
    'saleItem',
    'sale',
  ],
  finance: [
    'financeInvestment',
    'financeLedgerEntry',
    'financeExpense',
    'financeReconciliation',
    'financeTransfer',
    'cashierShift',
    'taxPayment',
    'taxReport',
    'taxReminder',
    'royaltyPayment',
    'royaltyInvoice',
  ],
  branchOrders: [
    'branchPayment',
    'branchOrderInstallment',
    'branchInvoice',
    'shortageResolution',
    'shortageReportItem',
    'shortageReport',
    'goodsReceivingItem',
    'goodsReceiving',
    'hqWarehousePickingTask',
    'hqStockBooking',
    'branchDistributionOrderItem',
    'branchDistributionOrder',
    'branchDistributionReceivingDraftRow',
    'branchDistributionReceivingDiscrepancy',
    'branchPurchaseRequestItem',
    'branchPurchaseRequest',
    'branchRequestIssue',
    'branchRequestShortage',
    'replacementShipmentItem',
    'replacementShipment',
  ],
  warehouse: [
    'distributionFifoAllocation',
    'fifoInventoryBatch',
    'stockMovement',
    'inventoryBalance',
    'inventoryCountItem',
    'inventoryCountSession',
    'chinaReceivingDraftRow',
    'chinaReceivingEditSession',
    'procurementGoodsReceivingItem',
    'procurementGoodsReceiving',
    'stockTransferItem',
    'stockTransfer',
    'warehouseReleaseOrderItem',
    'warehouseReleaseOrder',
    'partsConsumption',
    'partsRequestItem',
    'partsRequest',
  ],
  purchases: [
    'procurementDifferenceReport',
    'procurementLandedCostSnapshot',
    'procurementCostAdjustment',
    'procurementSupplierPayment',
    'procurementSvhToHqTransport',
    'procurementOrderItem',
    'procurementOrder',
    'procurementGoodsReceivingItem',
    'procurementGoodsReceiving',
    'chinaReceivingDraftRow',
    'chinaReceivingEditSession',
    'supplyInquiry',
    'purchaseOrderItem',
    'purchaseOrder',
    'containerTrackingEvent',
    'logisticsShipment',
    'supplierClaim',
  ],
  customers: [
    'followUp',
    'customerEvent',
    'customer',
  ],
  products: [
    'productPriceHistory',
    'productPurchasePriceHistory',
    'productPricingChangeHistory',
    'productCodeMigration',
    'pricingSimulation',
  ],
  employees: [
    'payrollRecord',
    'employeeKPI',
    'kpiSnapshot',
    'certificate',
    'enrollment',
    'student',
    'lesson',
    'course',
  ],
};

export const CLEANUP_COUNT_LABELS: Record<string, string> = {
  sale: 'Продажи',
  payment: 'Платежи',
  procurementOrder: 'Закупки',
  stockMovement: 'Складские движения',
  customer: 'Клиенты',
  product: 'Товары',
  productCategory: 'Категории товаров',
  user: 'Сотрудники',
  financeLedgerEntry: 'Финансовые операции',
  branchDistributionOrder: 'Заказы филиалов',
  fifoInventoryBatch: 'FIFO слои',
};
