ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasLogin" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "salary" DECIMAL(14,2);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
