export const NO_HQ_WAREHOUSE_ASSIGNED_TO_BRANCH = 'NO_HQ_WAREHOUSE_ASSIGNED_TO_BRANCH';
export const INACTIVE_HQ_WAREHOUSE = 'INACTIVE_HQ_WAREHOUSE';
export const NO_HQ_WAREHOUSE_MANAGER_ASSIGNED = 'NO_HQ_WAREHOUSE_MANAGER_ASSIGNED';
export const MANUAL_HQ_WAREHOUSE_SELECTION_FORBIDDEN = 'MANUAL_HQ_WAREHOUSE_SELECTION_FORBIDDEN';
