-- Expand service workflow enums before applying DRAFT defaults.

ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'MIXED';

ALTER TYPE "ServiceOrderStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "ServiceOrderStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "ServiceOrderStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_PAYMENT';
ALTER TYPE "ServiceOrderStatus" ADD VALUE IF NOT EXISTS 'PAID';

ALTER TYPE "PartsRequestStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "PartsRequestStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "PartsRequestStatus" ADD VALUE IF NOT EXISTS 'ISSUED';
ALTER TYPE "PartsRequestStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_ISSUED';
ALTER TYPE "PartsRequestStatus" ADD VALUE IF NOT EXISTS 'WAITING_STOCK';
ALTER TYPE "PartsRequestStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

ALTER TABLE "PartsRequest" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "ServiceOrder" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
