-- Finance Transfer: HQ Accountant prepares → HQ Cashier confirms with receipt

ALTER TYPE "FinanceTransferStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "FinanceTransferStatus" ADD VALUE IF NOT EXISTS 'PENDING_CASHIER';
ALTER TYPE "FinanceTransferStatus" ADD VALUE IF NOT EXISTS 'RETURNED';

ALTER TYPE "FileAttachmentEntityType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_RECEIPT';
ALTER TYPE "FileAttachmentEntityType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_SUPPORT';

ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_SENT_TO_CASHIER';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_RETURNED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_COMPLETED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_REVERSED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'FINANCE_TRANSFER_LARGE';
