-- Enums for payment information versions and transport expense workflow

ALTER TYPE "FileAttachmentEntityType" ADD VALUE IF NOT EXISTS 'TRANSPORT_EXPENSE_INVOICE';
ALTER TYPE "FileAttachmentEntityType" ADD VALUE IF NOT EXISTS 'TRANSPORT_EXPENSE_RECEIPT';

ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'TRANSPORT_EXPENSE_SUBMITTED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'TRANSPORT_EXPENSE_RETURNED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'TRANSPORT_EXPENSE_SENT_TO_CASHIER';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'TRANSPORT_EXPENSE_PAID';

DO $$ BEGIN
  CREATE TYPE "ProcurementPaymentInfoMethod" AS ENUM ('BANK_ACCOUNT', 'QR_CODE');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "TransportExpenseType" AS ENUM (
    'CHINA_WAREHOUSE',
    'DOMESTIC_CHINA_TRANSPORT',
    'INTERNATIONAL_FREIGHT',
    'CUSTOMS_BROKER',
    'LOCAL_DELIVERY',
    'OTHER_LOGISTICS'
  );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "TransportExpenseStatus" AS ENUM (
    'DRAFT',
    'WAITING_ACCOUNTANT',
    'RETURNED',
    'PENDING_CASHIER',
    'PAID',
    'CANCELLED'
  );
EXCEPTION WHEN duplicate_object THEN null;
END $$;
