-- Branch order review outcome notifications for Branch Sales

ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'BRANCH_ORDER_APPROVED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'BRANCH_ORDER_PARTIALLY_APPROVED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'BRANCH_ORDER_REJECTED';
